### ISSUE TITLE
Design change: light blue buffer > light green  

### ISSUE THREAD

**Issue by nellepierson** [dcfemtech/hackforgood-waba-map#116]
Please change grey buffer color to light green

The following css style can be added / modified for color adjustments: 
.leaflet-zoom-animated > g > path { fill: lightgreen; fill-opacity: 0.3; }

**Comment by alulsh** [comment]
> Please change grey buffer color to light green

Whoops, right now the buffers are light blue and set in lines 203-207 of `site.js` - https://github.com/dcfemtech/hackforgood-waba-map/blob/master/site.js#L203-L207.

```
        paint: {
            'fill-outline-color': '#1A3742',
            'fill-color': '#56B6DB',
            'fill-opacity': 0.5
        }
```

`lightgreen` is http://www.color-hex.com/color/90ee90 or `#90ee90` - is this the color you want @nellepierson? 

Attaching a screenshot of what it looks like:

![screenshot 2016-09-02 13 57 23](https://cloud.githubusercontent.com/assets/10409657/18213211/15bcb046-7115-11e6-987a-a997c065bafc.png)

**Comment by mdelcambre** [comment]
I went a shade darker than light green (#7bea7b), implemented the 30% opacity instead of 50% and made sure that the lanes were above the buffers so they didn't get lighter (as shown in the screenshot).

**Comment by alulsh** [comment]
Merged https://github.com/dcfemtech/hackforgood-waba-map/pull/126 so going to close this issue for now.

@nellepierson - if you want to make any further color changes, feel free to re-open and add another comment!
