### ISSUE TITLE
Map change: make all bike infrastructure the same green 

### ISSUE THREAD

**Issue by nellepierson** [dcfemtech/hackforgood-waba-map#118]
Sounds like the original plan was to make each county's bike infrastructure a different shade green. We decided we want the same green, now that we're adding in county boundary.

**Comment by mdelcambre** [comment]
I believe this is already fixed in master.

**Comment by nellepierson** [comment]
Oh! @mdelcambre, you're right. Thx!

**Comment by alulsh** [comment]
Yep - migrating to GL JS standardized the colors of the bike lanes 🙇 .
