### ISSUE TITLE
Update Fairfax County in data matrix

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#123]
At the moment the data matrix says the following for Fairfax County:

> This is a list of "suggested bike routes" (based on Bicycle Level of Service) and not true bike lanes so we have excluded this data set from the project.

We now have open data due to https://github.com/dcfemtech/hackforgood-waba-map/pull/99 🎉 

@alongthepike - can you update the data matrix with how you filtered the data + any relevant URLs from the Fairfax County GIS portal? 🙇

**Comment by alongthepike** [comment]
Fixed in #124
