### ISSUE TITLE
Create bike data source matrix

### ISSUE THREAD

**Issue by juliekdang** [dcfemtech/hackforgood-waba-map#15]
Create a matrix comparing the bike lane/trail data available from jurisdictions in the region, with T/F columns including:
- Historical lanes/trails
- Future/planned lanes/trails
- geojson format
- shape format
- last updated

This information may be needed to explain gaps in the data / functionality

**Comment by alulsh** [comment]
We have a decent data matrix right now! See screenshot below.

<img width="931" alt="screenshot 2016-08-16 23 47 26" src="https://cloud.githubusercontent.com/assets/10409657/17723936/097bd3ae-640c-11e6-9cbd-1b5deeef1cf3.png">

Nevertheless, our data matrix is missing how we got the data for DC (even though the data itself and http://opendata.dc.gov/ is excellent!).

Anybody want to do the following?

- [ ] Add DC data and URLs
- [ ] Add additional columns specified in https://github.com/dcfemtech/hackforgood-waba-map/issues/15#issue-162294428

**Comment by alulsh** [comment]
We created the initial bike data matrix - closing in favor of a new ticket on how to update our existing one!
