### ISSUE TITLE
add address label to geocoder marker

### ISSUE THREAD

**Issue by alexwweston** [dcfemtech/hackforgood-waba-map#24]
when the user searches for and selects an address, and an address marker appears, this marker should display the address

**Comment by alulsh** [comment]
I added this to display on click in https://github.com/dcfemtech/hackforgood-waba-map/pull/29.

Not sure if we want it to display on click or on load. We can ask WABA for their thoughts.

**Comment by alulsh** [comment]
Gonna close this - I think we are good to go in terms of the hackathon.
