### ISSUE TITLE
Add a geocoder control

### ISSUE THREAD

**Issue by juliekdang** [dcfemtech/hackforgood-waba-map#3]
As any user I want to enter an address (for e.g., my home) and have the map zoom to that location

**Comment by alexwweston** [comment]
@juliekdang should it add some sort of indicator to the map too? I'm thinking something like the google maps red bubble/flag thing that gets added when you enter a location.

**Comment by alexwweston** [comment]
Pretty much done! Just making sure master is error-free before I rebase my branch and make a pr. I ended up adding an indicator :-).
