### ISSUE TITLE
Control Layers

### ISSUE THREAD

**Issue by khiggins115** [dcfemtech/hackforgood-waba-map#32]
Map needs control layers panel (use Leafletjs's control layers) that sets 1mi buffer as default and allows users to check boxes to display multiple.

**Comment by alulsh** [comment]
http://leafletjs.com/examples/layers-control-example.html

**Comment by alulsh** [comment]
This is a complement to our existing drop down menu. This give people the option to select all the buffers at once!

We may need to tweak the color for each buffer layer in order for the visualization to be effective.

**Comment by alulsh** [comment]
Added in https://github.com/dcfemtech/hackforgood-waba-map/pull/47.
