### ISSUE TITLE
Add QGIS buffer docs

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#38]
@khiggins115 to create a `docs` folder and add buffer creation instructions in markdown.

**Comment by alulsh** [comment]
Found documentation on how to create buffers in QGIS: https://wiki.osgeo.org/wiki/Buffer_with_QGIS

**Comment by alulsh** [comment]
Found documentation on how to create buffers in QGIS: https://wiki.osgeo.org/wiki/Buffer_with_QGIS

**Comment by alongthepike** [comment]
Is this moot because we're adding the admin function to buffer in #74 ?

**Comment by alulsh** [comment]
> Is this moot because we're adding the admin function to buffer in #74 ?

@alongthepike - not necessarily, it would still be helpful to know how to create buffers in QGIS for troubleshooting purposes (or for when there's an issue with the turf-buffer npm module). Nevertheless, I wouldn't advocate for anybody to spend a lot of time writing these docs, especially when a tutorial, blog post, or official QGIS documentation would accomplish this instead.

**Comment by alulsh** [comment]
Closing as stale - the Node buffering approach is working really well!
