### ISSUE TITLE
Design a graphic look-and-feel 

### ISSUE THREAD

**Issue by juliekdang** [dcfemtech/hackforgood-waba-map#4]
Includes palette, fonts, and other graphic devices

**Comment by shannonturner** [comment]
Color palette is based off of the gradient on the homepage of the WABA website, which goes from #5d6d63 (grayish green) to #1a3742 (dark blue).

#56B6DB (light blue) is a nice color complement to #1a3742 (dark blue).
#323B35 (dark grayish green) is a nice color complement to #5d6d63 (grayish green).

With two dark colors and two light colors, the color palette looks like:

![image](https://cloud.githubusercontent.com/assets/3248065/16358385/9f7af3a4-3adf-11e6-81cb-ce7970f9c547.png)

**Comment by shannonturner** [comment]
I'd suggest we use Lato: https://fonts.google.com/specimen/Lato?selection.family=Lato

To use it we can embed this in the <head>: <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

And in the CSS we'd specify using: font-family: 'Lato', sans-serif;

**Comment by alulsh** [comment]
@nellepierson - what do you think of the above? Looks like we've tackled a lot of this in the tickets labeled `design` but is there anything else we are missing?

**Comment by nellepierson** [comment]
Agreed, we have "issue"'d all our design needs. If you're asking if this is closable I say "YEEHHH HAH!"
