### ISSUE TITLE
No Fairfax County bike lane data

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#41]
Whoops, the Fairfax County bike lane data is not actually bike lane data, instead it's "suggested bike routes" (aka roads under 35mph). We need to remove this.

**Comment by alulsh** [comment]
Fixed in https://github.com/dcfemtech/hackforgood-waba-map/pull/43.

**Comment by alulsh** [comment]
Re-opening this. We still don't have accurate bike lane data for Fairfax County, Virginia. Would be great to obtain this and add it to this project.

**Comment by alongthepike** [comment]
My bike/ped contact at Fairfax County never responded so I have sent a fresh email to the main GIS mailbox to see if I can drum anything up.  

As a temporary solution, we could look at extracting whatever bike lane information has been put into Open Street Map and using that in place of official data from the County.

I've done something similar in the past using [Overpass Turbo](https://www.mapbox.com/help/overpass-turbo/) for the data extraction.

**Comment by alongthepike** [comment]
Here is a zipped GeoJson of the Fairfax Bike Lanes that exist in OpenStreetMap as exported from Overpass Turbo if we decide this is the way to go until Fairfax gets its act together.

[VA_Fairfax_Bike_Lanes.zip](https://github.com/dcfemtech/hackforgood-waba-map/files/423031/VA_Fairfax_Bike_Lanes.zip)

**Comment by alongthepike** [comment]
Response from Fairfax County GIS:

> Thank you for using our online helpQ email. We are in the process of updating our open data bicycle layer. Please check it in couple of days. If you have any other questions, please let us know.
> 
> Thank you and have a great day!
> 
> 
> The HelpQ Team
> 12000 Government Center Parkway
> Fairfax, VA 22035

**Comment by alongthepike** [comment]
They weren't kidding - the Fairfax Bike Routes GIS data now includes Bike Lane locations.  I'll work to incorporate into the map.

**Comment by alulsh** [comment]
We have data!!!!!!!!!!!!!

💃 👯 🚲 

Thanks, everyone and thank you Fairfax County! 🙇 .
