### ISSUE TITLE
Fix Dropdown Menu

### ISSUE THREAD

**Issue by NealHumphrey** [dcfemtech/hackforgood-waba-map#57]
Dropdown menu currently not working (layers menu is working)

**Comment by NealHumphrey** [comment]
@alulsh: digging back through the code it looks like the dropdown menu was only ever connected to the dynamic rebuffer calculation, and was never connected to the preloaded buffers. So pulling the code out of the git history won't work. 

It's relatively simple to make the functions to do the filtering, but since I'm writing from scratch I'd rather approach it a bit more holistically. In particular, I'd like to refactor these variables:

```
var dcBuffer500 = L.mapbox.featureLayer().addTo(map);
var dcBuffer1000 = L.mapbox.featureLayer();
var dcBuffer2500 = L.mapbox.featureLayer();
var dcBuffer5280 = L.mapbox.featureLayer();
```

I'm thinking of adding a new category to the GeoJSON (i.e. buffer distance), so that we can merge all the data into one buffer variable and add a more universal filter function. This would allow us to more easily expand our filter/color coding criteria in the future (i.e. separated lanes vs. trails vs. standard, by county)

What do you think? Alternative is a quick and dirty toggle with our existing variables.

**Comment by NealHumphrey** [comment]
p.s. this could go hand-in-hand with the other function I mentioned (admin generate buffers) since I can custom fields to the GeoJSON as we parse it from each source - or at least set it up to be able to do so later.

**Comment by alulsh** [comment]
> we can merge all the data into one buffer variable

Can you elaborate on this point? We need four separate `featureLayers` for the four different buffers (for as long as we pre-generate buffers to workaround https://github.com/dcfemtech/hackforgood-waba-map/issues/1, which is explained in more depth in https://github.com/dcfemtech/hackforgood-waba-map/pull/8). This sounds like it would create only one `featureLayer` on the map.

> This would allow us to more easily expand our filter/color coding criteria in the future (i.e. separated lanes vs. trails vs. standard, by county)

This is great! I like the forward thinking 👍

**Comment by NealHumphrey** [comment]
Instead of adding and removing featureLayers from the map (``.featureLayer().addTo(map);``), I was thinking we'd put all the buffers into one layer and use [the setFilter function](https://www.mapbox.com/mapbox.js/api/v2.4.0/l-mapbox-featurelayer/) provided by featureLayer to toggle which ones are shown. 

At a minimum we can wrap the current variables in a map that directly connects the distance (e.g. 500 or 1000) to the featureLayer. Then you can iterate over them instead of having to manually maintain a list of which buffer layers you have anywhere you need to use it. Like this (note untested code example):
```
var buffer = {};
//.loadURL returns the layer object so it is what is assigned to the variable
buffer['500'] = L.mapbox.featureLayer().loadURL('./buffers/DC_Bike_Buffer_500ft.geojson')
buffer['1000'] = L.mapbox.featureLayer()

Object.keys(buffer).forEach(function (key) {
   console.log(key) //the distance, e.g. 500
   var currentLayer = buffer[key]
});
```

**Comment by tomBeach** [comment]
See comment for "Admin tool to generate buffers on demand" issue...

**Comment by alulsh** [comment]
No longer using a drop down menu after https://github.com/dcfemtech/hackforgood-waba-map/pull/78. Closing.
