### ISSUE TITLE
Remove red period from bike lane and buffer menu

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#81]
At the moment there's a red period in the bike lane and buffer menu when you are not moused over a jurisdiction or buffer selector.

This should instead be blank - no text - and not a red period.

<img width="318" alt="screenshot 2016-08-16 20 16 58" src="https://cloud.githubusercontent.com/assets/10409657/17720247/6f257e9e-63ee-11e6-9528-de455c8fd469.png">

**Comment by tomBeach** [comment]
Removed period from [index.html] (https://github.com/dcfemtech/hackforgood-waba-map/blob/master/index.html#L34) and "replacement" period in [site.js] (https://github.com/dcfemtech/hackforgood-waba-map/blob/master/site.js#L229), then changed css property from "inline-block" to "block" for [#hoverText] (https://github.com/dcfemtech/hackforgood-waba-map/blob/master/styles.css#L54)

**Comment by alulsh** [comment]
Fixed in https://github.com/dcfemtech/hackforgood-waba-map/pull/83! 🎉
