### ISSUE TITLE
User-friendly errors in the UI instead of console.log errors

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#87]
There are numerous `console.log` error messages for network (AJAX call) failures introduced in https://github.com/dcfemtech/hackforgood-waba-map/pull/78. There are also error messages for when data fails to load.

These errors currently use `console.log` statements instead of producing an error message in the UI. This is great for developers, but not so great for our target audience (who are *not* developers). We should instead use relatively unobtrusive modal dialogs (not annoying alert boxes) to display friendly error messages when data fails to load or other errors occur).

See my line note in https://github.com/dcfemtech/hackforgood-waba-map/pull/78#discussion_r74947183 for an example.

**Comment by onestepahead** [comment]
I have a branch with an error modal, but I don't think I have permission to submit a pull request. Can you check on that?

**Comment by alulsh** [comment]
> I have a branch with an error modal, but I don't think I have permission to submit a pull request. Can you check on that?

Welcome to the project @onestepahead! Even though I strongly prefer working on feature branches, mind submitting a PR from your own fork for now that I can review? 

I don't see any activity on your GitHub profile and am not sure if I've met you at Code for DC yet or not. Though I'm very open about granting write access to this repo, I generally only grant this quickly to people I meet at Code for DC or who are on the Code for DC Slack.

Feel free to email me with more information about yourself if you feel comfortable - my email address is in my GitHub profile.

**Comment by onestepahead** [comment]
@alulsh I'm Eric Fidler and we met last night. I think I gave you my old github account, @mobileric, which I don't have the login for anymore :(

**Comment by alulsh** [comment]
Oh yes we did meet at Code for DC last night! Access granted and email invite for write access to the repo sent.

**Comment by alulsh** [comment]
Closing as we no longer throw any errors to the user.
