### ISSUE TITLE
Refactor site.js

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#88]
https://github.com/dcfemtech/hackforgood-waba-map/pull/78 added awesome UI functionality but introduced 903 additional lines of code.

I think there's even more opportunities to refactor this file to slim down the main JavaScript codebase. Anybody want to tackle this?

**Comment by hrecht** [comment]
I'm working on https://github.com/dcfemtech/hackforgood-waba-map/issues/58 and site.js will need some major refactoring anyway to work with gl-js. Will work on slimming it down.

**Comment by hrecht** [comment]
Is there any particular reason for using jQuery v1 instead of v2?

**Comment by alulsh** [comment]
This was done in https://github.com/dcfemtech/hackforgood-waba-map/issues/58! Yay @hrecht! 👏 👏 👏
