### ISSUE TITLE
Fix colors for buffer layer

### ISSUE THREAD

**Issue by alulsh** [dcfemtech/hackforgood-waba-map#9]
I was unable to change the buffer layer from default gray to a different color. This needs to be fixed because the default gray is not visually striking.

Here is the code that's not working - https://github.com/dcfemtech/hackforgood-waba-map/blob/master/site.js#L23-L26

As you can see the code is calling for a hot pink color, but it's still showing up as gray.

**Comment by shannonturner** [comment]
My commit in e0274626438f76f7781ee1a1c8214b32a4217ff6 addresses this -- the Turf.js documentation is outdated or incorrect; each buffer.feature's properties needs to be set individually; it can't be set at the buffer level.

**Comment by alulsh** [comment]
Fixed by @sara4844 in https://github.com/dcfemtech/hackforgood-waba-map/pull/14! 🎉
