### ISSUE TITLE
Cleanup GeoJson Files

### ISSUE THREAD

**Issue by alongthepike** [dcfemtech/hackforgood-waba-map#95]
We've got some inconsistent names and extraneous geojson files laying around.  I think we should:

- [x]  Remove Fairfax
- [x]  Rename to STATE_Municipality.geojson
- [x]  Get rid of the Trail-only file for DC and the Lane-only file for DC since we aren't using them right now and they're simple to re-create.

**Comment by alulsh** [comment]
Expertly tackled by @alongthepike in https://github.com/dcfemtech/hackforgood-waba-map/pull/96 🙇 . Closing.
